[package]
authors = ["James Munns <james.munns@ferrous-systems.com>"]
name = "sprocket-boot"
edition = "2018"
version = "0.1.0"
license = "MPL-2.0"

[workspace]
members = [
    "testsuite",
    "vendor/stm32g0xx-hal",
    "crates/groundhog-stm32g031",
]

[dependencies]
cortex-m-rt = "0.6.13"
embedded-hal = "0.2.4"

[dependencies.cassette]
git = "https://github.com/jamesmunns/cassette"
branch = "main"

[dependencies.panic-reset]
version = "0.1"
optional = true

[dependencies.defmt]
version = "0.2.0"
optional = true

[dependencies.defmt-rtt]
version = "0.2.0"
optional = true

[dependencies.panic-probe]
version = "0.2.0"
features = ["print-defmt"]
optional = true

[dependencies.cortex-m]
version = "0.7.1"
features = ["inline-asm"]

[dependencies.stm32g0xx-hal]
path = "./vendor/stm32g0xx-hal"
features = ["rt", "stm32g031"]

[features]
# set logging levels here
default = [
  # "defmt-default",
  # "dependency-a/defmt-trace",
  "panic-reset",
]

# NOTE: To use the `defmt-log` feature, you must also
# modify `.cargo/config.toml` to add the defmt linker
# section!
#
# If you're using defmt, you probably also want to set
# the `skip-flash` feature, otherwise probe-run will
# disconnect whenever we interact with the flash memory
defmt-log = [
    "defmt",
    "defmt-rtt",
    "panic-probe",

    # Set defmt log level
    "defmt-default",
]

# Simulate flash operations for logging and testing
skip-flash = []

# do NOT modify these features
defmt-default = []
defmt-trace = []
defmt-debug = []
defmt-info = []
defmt-warn = []
defmt-error = []

# cargo build/run
[profile.dev]
codegen-units = 1
debug = 2
debug-assertions = true # <-
incremental = false
opt-level = 3 # <-
overflow-checks = true # <-

# cargo test
[profile.test]
codegen-units = 1
debug = 2
debug-assertions = true # <-
incremental = false
opt-level = 3 # <-
overflow-checks = true # <-

# cargo build/run --release
[profile.release]
codegen-units = 1
debug = 2
debug-assertions = false # <-
incremental = false
lto = 'fat'
opt-level = 's' # <-
overflow-checks = false # <-

# cargo test --release
[profile.bench]
codegen-units = 1
debug = 2
debug-assertions = false # <-
incremental = false
lto = 'fat'
opt-level = 3 # <-
overflow-checks = false # <-

# uncomment this to switch from the crates.io version of defmt to its git version
# check app-template's README for instructions
# [patch.crates-io]
# defmt = { git = "https://github.com/knurling-rs/defmt", rev = "use defmt version reported by `probe-run --version`" }
# defmt-rtt = { git = "https://github.com/knurling-rs/defmt", rev = "use defmt version reported by `probe-run --version`" }
# defmt-test = { git = "https://github.com/knurling-rs/defmt", rev = "use defmt version reported by `probe-run --version`" }
# panic-probe = { git = "https://github.com/knurling-rs/defmt", rev = "use defmt version reported by `probe-run --version`" }
